apiVersion: v1
kind: Service
metadata:
  name: sqs-local-aws-web
spec:
  selector:
    app: sqs-local-aws
  ports:
  - port: 9325
    targetPort: 9325


---
apiVersion: v1
kind: Service
metadata:
  name: sqs-local-aws-sqs
spec:
  selector:
    app: sqs-local-aws
  ports:
  - port: 9324
    targetPort: 9324

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-local-aws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqs-local-aws
  template:
    metadata:
      labels:
        app: sqs-local-aws
    spec:
      containers:
      - name: sqs-local-aws
        image: roribio16/alpine-sqs:latest
        ports:
        - containerPort: 9324
          name: sqs
        - containerPort: 9325
          name: web

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sqs-local-aws
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: sqs-web.henrynetworks.com
    http:
      paths:
      - backend:
          serviceName: sqs-local-aws-web
          servicePort: 9325
  - host: sqs.henrynetworks.com
    http:
      paths:
      - backend:
          serviceName: sqs-local-aws-sqs
          servicePort: 9324